package = {
    spec        = "1",
    namespace   = "compat",
    name        = "compat.xz",
    description = "XZ Utils liblzma compression library",
    licenses    = {"0BSD"},
    repo        = "https://github.com/tukaani-project/xz",
    type        = "package",

    xpm = {
        linux = {
            ["5.8.3"] = {
                url    = {
                    GLOBAL = "https://github.com/tukaani-project/xz/releases/download/v5.8.3/xz-5.8.3.tar.gz",
                    CN     = "https://gitcode.com/mcpp-res/xz/releases/download/5.8.3/xz-5.8.3.tar.gz",
                },
                sha256 = "3d3a1b973af218114f4f889bbaa2f4c037deaae0c8e815eec381c3d546b974a0",
            },
        },
        macosx = {
            ["5.8.3"] = {
                url    = {
                    GLOBAL = "https://github.com/tukaani-project/xz/releases/download/v5.8.3/xz-5.8.3.tar.gz",
                    CN     = "https://gitcode.com/mcpp-res/xz/releases/download/5.8.3/xz-5.8.3.tar.gz",
                },
                sha256 = "3d3a1b973af218114f4f889bbaa2f4c037deaae0c8e815eec381c3d546b974a0",
            },
        },
        windows = {
            ["5.8.3"] = {
                url    = {
                    GLOBAL = "https://github.com/tukaani-project/xz/releases/download/v5.8.3/xz-5.8.3.tar.gz",
                    CN     = "https://gitcode.com/mcpp-res/xz/releases/download/5.8.3/xz-5.8.3.tar.gz",
                },
                sha256 = "3d3a1b973af218114f4f889bbaa2f4c037deaae0c8e815eec381c3d546b974a0",
            },
        },
    },

    mcpp = {
        language   = "c++23",
        import_std = false,
        c_standard = "c11",
        include_dirs = {
            "*/src/liblzma/api",
            "*/src/liblzma/common",
            "*/src/liblzma/check",
            "*/src/liblzma/lz",
            "*/src/liblzma/rangecoder",
            "*/src/liblzma/lzma",
            "*/src/liblzma/delta",
            "*/src/liblzma/simple",
            "*/src/common",
        },
        cflags = {
            "-D_GNU_SOURCE",
            "-DSIZEOF_SIZE_T=8",
            "-DHAVE_STDBOOL_H=1",
            "-DHAVE__BOOL=1",
            "-DHAVE_STDINT_H=1",
            "-DHAVE_INTTYPES_H=1",
            "-DTUKLIB_SYMBOL_PREFIX=lzma_",
            "-DHAVE_CHECK_CRC32=1",
            "-DHAVE_CHECK_CRC64=1",
            "-DHAVE_CHECK_SHA256=1",
            "-DHAVE_ENCODERS=1",
            "-DHAVE_DECODERS=1",
            "-DHAVE_ENCODER_LZMA1=1",
            "-DHAVE_ENCODER_LZMA2=1",
            "-DHAVE_ENCODER_DELTA=1",
            "-DHAVE_ENCODER_X86=1",
            "-DHAVE_ENCODER_POWERPC=1",
            "-DHAVE_ENCODER_IA64=1",
            "-DHAVE_ENCODER_ARM=1",
            "-DHAVE_ENCODER_ARMTHUMB=1",
            "-DHAVE_ENCODER_ARM64=1",
            "-DHAVE_ENCODER_SPARC=1",
            "-DHAVE_ENCODER_RISCV=1",
            "-DHAVE_DECODER_LZMA1=1",
            "-DHAVE_DECODER_LZMA2=1",
            "-DHAVE_DECODER_DELTA=1",
            "-DHAVE_DECODER_X86=1",
            "-DHAVE_DECODER_POWERPC=1",
            "-DHAVE_DECODER_IA64=1",
            "-DHAVE_DECODER_ARM=1",
            "-DHAVE_DECODER_ARMTHUMB=1",
            "-DHAVE_DECODER_ARM64=1",
            "-DHAVE_DECODER_SPARC=1",
            "-DHAVE_DECODER_RISCV=1",
            "-DHAVE_LZIP_DECODER=1",
            "-DHAVE_MF_HC3=1",
            "-DHAVE_MF_HC4=1",
            "-DHAVE_MF_BT2=1",
            "-DHAVE_MF_BT3=1",
            "-DHAVE_MF_BT4=1",
        },
        sources = {
            "*/src/common/tuklib_physmem.c",
            "*/src/liblzma/check/check.c",
            "*/src/liblzma/check/crc32_fast.c",
            "*/src/liblzma/check/crc64_fast.c",
            "*/src/liblzma/check/sha256.c",
            "*/src/liblzma/common/alone_decoder.c",
            "*/src/liblzma/common/alone_encoder.c",
            "*/src/liblzma/common/auto_decoder.c",
            "*/src/liblzma/common/block_buffer_decoder.c",
            "*/src/liblzma/common/block_buffer_encoder.c",
            "*/src/liblzma/common/block_decoder.c",
            "*/src/liblzma/common/block_encoder.c",
            "*/src/liblzma/common/block_header_decoder.c",
            "*/src/liblzma/common/block_header_encoder.c",
            "*/src/liblzma/common/block_util.c",
            "*/src/liblzma/common/common.c",
            "*/src/liblzma/common/easy_buffer_encoder.c",
            "*/src/liblzma/common/easy_decoder_memusage.c",
            "*/src/liblzma/common/easy_encoder.c",
            "*/src/liblzma/common/easy_encoder_memusage.c",
            "*/src/liblzma/common/easy_preset.c",
            "*/src/liblzma/common/file_info.c",
            "*/src/liblzma/common/filter_buffer_decoder.c",
            "*/src/liblzma/common/filter_buffer_encoder.c",
            "*/src/liblzma/common/filter_common.c",
            "*/src/liblzma/common/filter_decoder.c",
            "*/src/liblzma/common/filter_encoder.c",
            "*/src/liblzma/common/filter_flags_decoder.c",
            "*/src/liblzma/common/filter_flags_encoder.c",
            "*/src/liblzma/common/hardware_physmem.c",
            "*/src/liblzma/common/index.c",
            "*/src/liblzma/common/index_decoder.c",
            "*/src/liblzma/common/index_encoder.c",
            "*/src/liblzma/common/index_hash.c",
            "*/src/liblzma/common/lzip_decoder.c",
            "*/src/liblzma/common/microlzma_decoder.c",
            "*/src/liblzma/common/microlzma_encoder.c",
            "*/src/liblzma/common/stream_buffer_decoder.c",
            "*/src/liblzma/common/stream_buffer_encoder.c",
            "*/src/liblzma/common/stream_decoder.c",
            "*/src/liblzma/common/stream_encoder.c",
            "*/src/liblzma/common/stream_flags_common.c",
            "*/src/liblzma/common/stream_flags_decoder.c",
            "*/src/liblzma/common/stream_flags_encoder.c",
            "*/src/liblzma/common/string_conversion.c",
            "*/src/liblzma/common/vli_decoder.c",
            "*/src/liblzma/common/vli_encoder.c",
            "*/src/liblzma/common/vli_size.c",
            "*/src/liblzma/delta/delta_common.c",
            "*/src/liblzma/delta/delta_decoder.c",
            "*/src/liblzma/delta/delta_encoder.c",
            "*/src/liblzma/lz/lz_decoder.c",
            "*/src/liblzma/lz/lz_encoder.c",
            "*/src/liblzma/lz/lz_encoder_mf.c",
            "*/src/liblzma/lzma/fastpos_table.c",
            "*/src/liblzma/lzma/lzma2_decoder.c",
            "*/src/liblzma/lzma/lzma2_encoder.c",
            "*/src/liblzma/lzma/lzma_decoder.c",
            "*/src/liblzma/lzma/lzma_encoder.c",
            "*/src/liblzma/lzma/lzma_encoder_optimum_fast.c",
            "*/src/liblzma/lzma/lzma_encoder_optimum_normal.c",
            "*/src/liblzma/lzma/lzma_encoder_presets.c",
            "*/src/liblzma/rangecoder/price_table.c",
            "*/src/liblzma/simple/arm.c",
            "*/src/liblzma/simple/arm64.c",
            "*/src/liblzma/simple/armthumb.c",
            "*/src/liblzma/simple/ia64.c",
            "*/src/liblzma/simple/powerpc.c",
            "*/src/liblzma/simple/riscv.c",
            "*/src/liblzma/simple/simple_coder.c",
            "*/src/liblzma/simple/simple_decoder.c",
            "*/src/liblzma/simple/simple_encoder.c",
            "*/src/liblzma/simple/sparc.c",
            "*/src/liblzma/simple/x86.c",
        },
        targets = { ["xz"] = { kind = "lib" } },
        deps    = {},
    },
}
