package = {
    spec        = "1",
    namespace   = "compat",
    name        = "compat.libarchive",
    description = "Multi-format archive and compression library",
    licenses    = {"BSD-2-Clause"},
    repo        = "https://libarchive.org/",
    type        = "package",

    xpm = {
        linux = {
            ["3.8.7"] = {
                url    = "https://libarchive.org/downloads/libarchive-3.8.7.tar.gz",
                sha256 = "4b787cca6697a95c7725e45293c973c208cbdc71ae2279f30ef09f52472b9166",
            },
        },
        macosx = {
            ["3.8.7"] = {
                url    = "https://libarchive.org/downloads/libarchive-3.8.7.tar.gz",
                sha256 = "4b787cca6697a95c7725e45293c973c208cbdc71ae2279f30ef09f52472b9166",
            },
        },
        windows = {
            ["3.8.7"] = {
                url    = "https://github.com/libarchive/libarchive/archive/refs/tags/v3.8.7.zip",
                sha256 = "8e16ac8797510144ab71ead4181ea1efb28e036b9fed283e57490ea39b8180d2",
            },
        },
    },

    mcpp = {
        language     = "c++23",
        import_std   = false,
        c_standard   = "c11",
        include_dirs = {"*", "*/libarchive", "mcpp_generated/include"},
        cflags       = {
            "-D_GNU_SOURCE",
            "-DLIBARCHIVE_STATIC",
            "-DPLATFORM_CONFIG_H=\\\"mcpp_libarchive_config.h\\\"",
        },
        generated_files = {
            ["mcpp_generated/include/localcharset.h"] = "#pragma once\nstatic inline const char* locale_charset(void) { return \"UTF-8\"; }\n",
            ["mcpp_generated/include/mcpp_libarchive_config.h"] = "#pragma once\n#if defined(_WIN32) && !defined(__CYGWIN__)\n#include \"contrib/android/config/windows_host.h\"\n#else\n#include \"contrib/android/config/linux_host.h\"\n#endif\n#define __LIBARCHIVE_CONFIG_H_INCLUDED 1\n#if !defined(__linux__)\n#undef HAVE_LINUX_FIEMAP_H\n#undef HAVE_LINUX_FS_H\n#undef HAVE_LINUX_MAGIC_H\n#undef HAVE_LINUX_TYPES_H\n#undef HAVE_SYS_STATFS_H\n#undef HAVE_SYS_VFS_H\n#endif\n#if defined(__APPLE__)\n#undef HAVE_STRUCT_STAT_ST_MTIM_TV_NSEC\n#define HAVE_STRUCT_STAT_ST_MTIMESPEC_TV_NSEC 1\n#undef HAVE_FUTIMESAT\n#undef HAVE_ICONV\n#undef HAVE_ICONV_H\n#endif\n#if defined(_WIN32) && !defined(__CYGWIN__)\n#include <stddef.h>\n#pragma comment(lib, \"advapi32.lib\")\n#pragma comment(lib, \"xmllite.lib\")\n#undef HAVE_UNISTD_H\n#undef HAVE_DECL_SSIZE_MAX\n#define HAVE_DECL_SSIZE_MAX 0\n#define HAVE__GET_TIMEZONE 1\ntypedef ptrdiff_t ssize_t;\ntypedef int pid_t;\ntypedef unsigned short mode_t;\n#ifndef PROV_RSA_AES\n#define PROV_RSA_AES 24\n#endif\n#ifndef CALG_SHA_256\n#define CALG_SHA_256 0x0000800c\n#endif\n#ifndef CALG_SHA_384\n#define CALG_SHA_384 0x0000800d\n#endif\n#ifndef CALG_SHA_512\n#define CALG_SHA_512 0x0000800e\n#endif\n#endif\n#undef HAVE_BZLIB_H\n#define HAVE_BZLIB_H 1\n#undef HAVE_LIBBZ2\n#define HAVE_LIBBZ2 1\n#undef HAVE_LIBLZ4\n#define HAVE_LIBLZ4 1\n#undef HAVE_LIBLZMA\n#define HAVE_LIBLZMA 1\n#undef HAVE_LIBZ\n#define HAVE_LIBZ 1\n#undef HAVE_LIBZSTD\n#define HAVE_LIBZSTD 1\n#undef HAVE_LZ4_H\n#define HAVE_LZ4_H 1\n#undef HAVE_LZ4HC_H\n#define HAVE_LZ4HC_H 1\n#undef HAVE_LZMA_H\n#define HAVE_LZMA_H 1\n#undef HAVE_LZMA_STREAM_ENCODER_MT\n#undef HAVE_ZLIB_H\n#define HAVE_ZLIB_H 1\n#undef HAVE_ZSTD_H\n#define HAVE_ZSTD_H 1\n#undef HAVE_ZSTD_compressStream\n#define HAVE_ZSTD_compressStream 1\n#undef HAVE_ZSTD_minCLevel\n#define HAVE_ZSTD_minCLevel 1\n#undef HAVE_LOCALCHARSET_H\n#define HAVE_LOCALCHARSET_H 1\n#undef HAVE_LOCALE_CHARSET\n#define HAVE_LOCALE_CHARSET 1\n#undef HAVE_CLOSEFROM\n#define HAVE_CLOSEFROM 0\n#undef HAVE_CLOSE_RANGE\n#define HAVE_CLOSE_RANGE 0\n#ifndef HAVE_DECL_INT32_MAX\n#define HAVE_DECL_INT32_MAX 1\n#endif\n#ifndef HAVE_DECL_INT32_MIN\n#define HAVE_DECL_INT32_MIN 1\n#endif\n#ifndef HAVE_DECL_UINTMAX_MAX\n#define HAVE_DECL_UINTMAX_MAX 1\n#endif\n#ifndef HAVE_DECL_INTMAX_MAX\n#define HAVE_DECL_INTMAX_MAX 1\n#endif\n#ifndef HAVE_DECL_INTMAX_MIN\n#define HAVE_DECL_INTMAX_MIN 1\n#endif\n",
        },
        sources = {
            "*/libarchive/archive_acl.c",
            "*/libarchive/archive_blake2s_ref.c",
            "*/libarchive/archive_blake2sp_ref.c",
            "*/libarchive/archive_check_magic.c",
            "*/libarchive/archive_cmdline.c",
            "*/libarchive/archive_cryptor.c",
            "*/libarchive/archive_digest.c",
            "*/libarchive/archive_entry.c",
            "*/libarchive/archive_entry_copy_stat.c",
            "*/libarchive/archive_entry_link_resolver.c",
            "*/libarchive/archive_entry_sparse.c",
            "*/libarchive/archive_entry_stat.c",
            "*/libarchive/archive_entry_strmode.c",
            "*/libarchive/archive_entry_xattr.c",
            "*/libarchive/archive_hmac.c",
            "*/libarchive/archive_match.c",
            "*/libarchive/archive_options.c",
            "*/libarchive/archive_pack_dev.c",
            "*/libarchive/archive_parse_date.c",
            "*/libarchive/archive_pathmatch.c",
            "*/libarchive/archive_ppmd8.c",
            "*/libarchive/archive_ppmd7.c",
            "*/libarchive/archive_random.c",
            "*/libarchive/archive_rb.c",
            "*/libarchive/archive_read.c",
            "*/libarchive/archive_read_add_passphrase.c",
            "*/libarchive/archive_read_append_filter.c",
            "*/libarchive/archive_read_data_into_fd.c",
            "*/libarchive/archive_read_disk_entry_from_file.c",
            "*/libarchive/archive_read_disk_posix.c",
            "*/libarchive/archive_read_disk_windows.c",
            "*/libarchive/archive_read_disk_set_standard_lookup.c",
            "*/libarchive/archive_read_extract.c",
            "*/libarchive/archive_read_extract2.c",
            "*/libarchive/archive_read_open_fd.c",
            "*/libarchive/archive_read_open_file.c",
            "*/libarchive/archive_read_open_filename.c",
            "*/libarchive/archive_read_open_memory.c",
            "*/libarchive/archive_read_set_format.c",
            "*/libarchive/archive_read_set_options.c",
            "*/libarchive/archive_read_support_filter_all.c",
            "*/libarchive/archive_read_support_filter_by_code.c",
            "*/libarchive/archive_read_support_filter_bzip2.c",
            "*/libarchive/archive_read_support_filter_compress.c",
            "*/libarchive/archive_read_support_filter_gzip.c",
            "*/libarchive/archive_read_support_filter_grzip.c",
            "*/libarchive/archive_read_support_filter_lrzip.c",
            "*/libarchive/archive_read_support_filter_lz4.c",
            "*/libarchive/archive_read_support_filter_lzop.c",
            "*/libarchive/archive_read_support_filter_none.c",
            "*/libarchive/archive_read_support_filter_program.c",
            "*/libarchive/archive_read_support_filter_rpm.c",
            "*/libarchive/archive_read_support_filter_uu.c",
            "*/libarchive/archive_read_support_filter_xz.c",
            "*/libarchive/archive_read_support_filter_zstd.c",
            "*/libarchive/archive_read_support_format_7zip.c",
            "*/libarchive/archive_read_support_format_all.c",
            "*/libarchive/archive_read_support_format_ar.c",
            "*/libarchive/archive_read_support_format_by_code.c",
            "*/libarchive/archive_read_support_format_cab.c",
            "*/libarchive/archive_read_support_format_cpio.c",
            "*/libarchive/archive_read_support_format_empty.c",
            "*/libarchive/archive_read_support_format_iso9660.c",
            "*/libarchive/archive_read_support_format_lha.c",
            "*/libarchive/archive_read_support_format_mtree.c",
            "*/libarchive/archive_read_support_format_rar.c",
            "*/libarchive/archive_read_support_format_rar5.c",
            "*/libarchive/archive_read_support_format_raw.c",
            "*/libarchive/archive_read_support_format_tar.c",
            "*/libarchive/archive_read_support_format_warc.c",
            "*/libarchive/archive_read_support_format_xar.c",
            "*/libarchive/archive_read_support_format_zip.c",
            "*/libarchive/archive_string.c",
            "*/libarchive/archive_string_sprintf.c",
            "*/libarchive/archive_time.c",
            "*/libarchive/archive_util.c",
            "*/libarchive/archive_version_details.c",
            "*/libarchive/archive_virtual.c",
            "*/libarchive/archive_windows.c",
            "*/libarchive/archive_write.c",
            "*/libarchive/archive_write_disk_posix.c",
            "*/libarchive/archive_write_disk_windows.c",
            "*/libarchive/archive_write_disk_set_standard_lookup.c",
            "*/libarchive/archive_write_open_fd.c",
            "*/libarchive/archive_write_open_file.c",
            "*/libarchive/archive_write_open_filename.c",
            "*/libarchive/archive_write_open_memory.c",
            "*/libarchive/archive_write_add_filter.c",
            "*/libarchive/archive_write_add_filter_b64encode.c",
            "*/libarchive/archive_write_add_filter_by_name.c",
            "*/libarchive/archive_write_add_filter_bzip2.c",
            "*/libarchive/archive_write_add_filter_compress.c",
            "*/libarchive/archive_write_add_filter_grzip.c",
            "*/libarchive/archive_write_add_filter_gzip.c",
            "*/libarchive/archive_write_add_filter_lrzip.c",
            "*/libarchive/archive_write_add_filter_lz4.c",
            "*/libarchive/archive_write_add_filter_lzop.c",
            "*/libarchive/archive_write_add_filter_none.c",
            "*/libarchive/archive_write_add_filter_program.c",
            "*/libarchive/archive_write_add_filter_uuencode.c",
            "*/libarchive/archive_write_add_filter_xz.c",
            "*/libarchive/archive_write_add_filter_zstd.c",
            "*/libarchive/archive_write_set_format.c",
            "*/libarchive/archive_write_set_format_7zip.c",
            "*/libarchive/archive_write_set_format_ar.c",
            "*/libarchive/archive_write_set_format_by_name.c",
            "*/libarchive/archive_write_set_format_cpio.c",
            "*/libarchive/archive_write_set_format_cpio_binary.c",
            "*/libarchive/archive_write_set_format_cpio_newc.c",
            "*/libarchive/archive_write_set_format_cpio_odc.c",
            "*/libarchive/archive_write_set_format_filter_by_ext.c",
            "*/libarchive/archive_write_set_format_gnutar.c",
            "*/libarchive/archive_write_set_format_iso9660.c",
            "*/libarchive/archive_write_set_format_mtree.c",
            "*/libarchive/archive_write_set_format_pax.c",
            "*/libarchive/archive_write_set_format_raw.c",
            "*/libarchive/archive_write_set_format_shar.c",
            "*/libarchive/archive_write_set_format_ustar.c",
            "*/libarchive/archive_write_set_format_v7tar.c",
            "*/libarchive/archive_write_set_format_warc.c",
            "*/libarchive/archive_write_set_format_xar.c",
            "*/libarchive/archive_write_set_format_zip.c",
            "*/libarchive/archive_write_set_options.c",
            "*/libarchive/archive_write_set_passphrase.c",
            "*/libarchive/filter_fork_posix.c",
            "*/libarchive/filter_fork_windows.c",
            "*/libarchive/xxhash.c",
        },
        targets = { ["libarchive"] = { kind = "lib" } },
        deps = {
            ["compat.zlib"]  = "1.3.2",
            ["compat.bzip2"] = "1.0.8",
            ["compat.lz4"]   = "1.10.0",
            ["compat.zstd"]  = "1.5.7",
            ["compat.xz"]    = "5.8.3",
        },
    },
}
